services:
  - type: web
    name: m3u8-downloader
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: API_ID
        value: your_api_id_here
      - key: API_HASH
        value: your_api_hash_here
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: DOWNLOAD_DIR
        value: ./downloads
